[{
    "iconOff": "ic_check_box_unchecked",
    "iconOn": "ic_check_box_checked",
    "offColor": -1,
    "onColor": -1,
    "payloadOff": "0",
    "payloadOn": "1",
    "enableIntermediateState": true,
    "enablePub": true,
    "enteredIntermediateStateAt": 0,
    "intermediateStateTimeout": 0,
    "jsOnReceive": "",
    "jsonPath": "",
    "lastPayload": "1",
    "qos": 0,
    "retained": true,
    "topic": "/devices/wb-gpio/controls/LIGHT_HALL1/on",
    "topicPub": "",
    "updateLastPayloadOnPub": true,
    "id": "901c9de5-5f26-49d8-9197-e350b8fc5ce3",
    "jsBlinkExpresskjkjkjkkjkjkjk,k,kj ,kh,kh,kh ,kh        gg g g g g g g ggghghgjhsfgfgfgfgfgfgffffgfgfgfggfhgfhgfhgfion": "",
    "jsOnDisplay": "",
    "jsOnTap": "",
    "lastActivity": 1510948363,
    "longId": 1,
    "name": "hall",
    "type": 2
}]